CREATE TABLE CLIENTE{
	CLINETE_ID 	NUMBER(3,0)	AUTO_INCREMENT NOT NULL,
	NOMBRE		VARCHAR(50)	NOT NULL,
	DIRECCION	VARCHAR(50)	NOT NULL,
	CONSTRAINT PK_1 PRIMARY KEY (CLINETE_ID)
};
CREATE TABLE FACTURA{
	FACTURA_ID	NUMBER(3,0)	AUTO_INCREMENT NOT NULL,
	MONTO		NUMBER(6,0)	NOT NULL,
	CONSTRAINT PK_2 PRIMARY KEY (FACTURA_ID)
};
CREATE TABLE VEHICULO{
	VEHICULO_ID	NUMBER(3,0)	AUTO_INCREMENT NOT NULL,
	PLACA		NUMBER(8,0)	NOT NULL,
	MARCA		VARCHAR(20)	NOT NULL,
	MODELO		VARCHAR(20)	NOT NULL,
	FACTURA_ID	NUMBER(3,0)	NOT NULL,
	CONSTRAINT PK_3 PRIMARY KEY (VEHICULO_ID),
	CONSTRAINT refFactura FOREIGN KEY (FACTURA_ID)
	REFERENCES FACTURA(FACTURA_ID)
};